// YoniTube background.js v10
'use strict';
const SRV = 'http://127.0.0.1:5000';

const SK  = 'yn_s_v6';
const SK_OLD = 'yn_s_v5';

let _lastCookieExportTs = 0;
let _lastCookieExportHash = '';
const COOKIE_THROTTLE_MS = 60000;
const COOKIE_DOMAINS = ['.youtube.com','youtube.com','.music.youtube.com','music.youtube.com','.google.com','google.com','.accounts.google.com','accounts.google.com'];

function _hashString(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) - h) + str.charCodeAt(i);
    h |= 0;
  }
  return String(h);
}

function _loadSettings(cb) {
  chrome.storage.local.get([SK, SK_OLD], r => {
    cb(Object.assign({}, r[SK_OLD] || {}, r[SK] || {}));
  });
}

function _isYoutubeRelevantCookie(c) {
  const domain = (c.domain || '').toLowerCase().replace(/^\./, '');
  if (domain === 'youtube.com' || domain.endsWith('.youtube.com')) return true;
  if (domain === 'music.youtube.com') return true;
  // Root Google auth cookies only — exclude chat/mail/drive/docs subdomains
  if (domain === 'google.com') return true;
  if (domain === 'accounts.google.com') return true;
  return false;
}

function _cookiesToNetscape(cookies) {
  let txt = '# Netscape HTTP Cookie File\n# Generated by YoniTube\n\n';
  (cookies || []).forEach(c => {
    if (!_isYoutubeRelevantCookie(c)) return;
    const val = c.value == null ? '' : String(c.value);
    if (val.includes('\t') || val.includes('\n') || val.includes('\r')) return;
    const httpOnly = c.httpOnly ? '#HttpOnly_' : '';
    const domain = c.domain.startsWith('.') ? c.domain : (c.hostOnly ? c.domain : '.' + c.domain);
    const flag = (c.domain.startsWith('.') || !c.hostOnly) ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const exp = c.expirationDate ? Math.round(c.expirationDate) : 0;
    txt += `${httpOnly}${domain}\t${flag}\t${c.path || '/'}\t${secure}\t${exp}\t${c.name}\t${val}\n`;
  });
  return txt;
}

async function _exportYoutubeCookies(force) {
  try {
    const now = Date.now();
    if (!force && now - _lastCookieExportTs < COOKIE_THROTTLE_MS) return;
    // Collect cookies from all relevant domains (matching popup COOKIE_DOMAINS)
    const raw = [];
    for (const d of COOKIE_DOMAINS) {
      try {
        const arr = await chrome.cookies.getAll({ domain: d });
        for (const c of arr || []) {
          if (c?.name) raw.push(c);
        }
      } catch {}
    }
    // Deduplicate by (domain, path, name)
    const seen = new Set();
    const cookies = [];
    for (const c of raw) {
      if (!_isYoutubeRelevantCookie(c)) continue;
      const key = `${c.domain}\t${c.path}\t${c.name}`;
      if (seen.has(key)) continue;
      seen.add(key);
      cookies.push(c);
    }
    if (!cookies.length) return;
    const txt = _cookiesToNetscape(cookies);
    const hash = _hashString(txt);
    if (!force && hash === _lastCookieExportHash) {
      _lastCookieExportTs = now;
      return;
    }
    _lastCookieExportHash = hash;
    _lastCookieExportTs = now;
    await fetch(SRV + '/update_cookies', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ cookies_txt: txt }),
    });
  } catch {}
}

function _sendToServer(body) {
  _exportYoutubeCookies(true).finally(() => {
    fetch(SRV + '/download', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    }).then(r => r.json()).then(d => {
      _bgSaveQueuedItem(d, body);
    }).catch(() => {});
  });
}

// ── Context menu ──────────────────────────────────────────────────
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.removeAll(() => {
    const C = (id, title, parentId) => chrome.contextMenus.create(
      { id, title, ...(parentId ? {parentId} : {}),
        contexts: ['video'],
        documentUrlPatterns: ['*://*.youtube.com/*','*://music.youtube.com/*'] }
    );
    C('yn-root',  '⬇ YoniTube הורד');
    C('yn-mp3',    '🎵 MP3 (אודיו)',        'yn-root');
    C('yn-m4a',    '🎵 M4A (אודיו)',        'yn-root');
    C('yn-mp4',    '🎬 MP4 — הכי טוב',      'yn-root');
    C('yn-1080',   '📺 MP4 — 1080p',        'yn-root');
    C('yn-720',    '📺 MP4 — 720p',         'yn-root');
    C('yn-480',    '📺 MP4 — 480p',         'yn-root');
    C('yn-mkv',    '📦 MKV (עם כתוביות)',   'yn-root');
    C('yn-thumb',  '📷 תמונת עטיפה',       'yn-root');
    C('yn-sep',    '─────────────────',     'yn-root');
    C('yn-popup',  '📋 פתח תפריט מלא...',  'yn-root');
  });
});

const _FMT_MAP = {
  'yn-mp3':  { format: 'mp3' },
  'yn-m4a':  { format: 'm4a' },
  'yn-mp4':  { format: 'mp4' },
  'yn-1080': { format: 'mp4', height: 1080 },
  'yn-720':  { format: 'mp4', height: 720  },
  'yn-480':  { format: 'mp4', height: 480  },
  'yn-mkv':  { format: 'mkv' },
  'yn-thumb':{ format: 'thumbnail' },
};

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  const rawUrl = info.linkUrl || info.srcUrl || info.pageUrl || '';
  if (!rawUrl) return;

  if (info.menuItemId === 'yn-sep') return;

  if (info.menuItemId === 'yn-popup') {
    // Open the popup directly
    chrome.action.openPopup?.().catch(() => {});
    return;
  }

  const fmtInfo = _FMT_MAP[info.menuItemId];
  if (fmtInfo) {
    _loadSettings(s => {
      const body = { url: rawUrl, speed: s.defSpeed || 'medium', ...fmtInfo };
      if (s.basePath) body.base_path = s.basePath;
      if (s.folderPlaylist) body.folder_playlist = true;
      if (s.folderChannel) body.folder_channel = true;
      _sendToServer(body);
    });
  }
});

// ── Queue persistence helper (belt-and-suspenders: background writes uid
//    so even if content script context is destroyed, popup still sees item)
function _bgSaveQueuedItem(d, body) {
  if (!d || !d.uid) return;
  try {
    chrome.storage.local.get(['yn_qItems','yn_deleted_uids'], (r) => {
      try {
        const q = r.yn_qItems || {};
        const dels = new Set(r.yn_deleted_uids || []);
        if (dels.has(d.uid)) dels.delete(d.uid);
        if (!q[d.uid]) {
          const b = body || {};
          q[d.uid] = {
            uid: d.uid,
            title: d.title || b.title || '',
            format: d.format || b.format || '',
            pct: 0,
            status: 'queued',
            source: 'youtube',
            thumb: d.thumb || b.thumb || '',
            url: b.url || ''
          };
          chrome.storage.local.set({
            'yn_qItems': q,
            'yn_deleted_uids': Array.from(dels)
          });
        }
      } catch(e) {}
    });
  } catch(e) {}
}

// ── Message relay ─────────────────────────────────────────────────
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.target === 'offscreen') return false;

  if (msg.type === 'download' || msg.type === 'downloadWithCookies') {
    const body = msg.body || {};
    _exportYoutubeCookies(true).finally(() => {
      fetch(SRV + '/download', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      }).then(r => r.json())
        .then(d => {
          _bgSaveQueuedItem(d, body);
          sendResponse({ ok: true, data: d });
        })
        .catch(e => sendResponse({ ok: false, error: String(e) }));
    });
    return true;
  }

  if (msg.type === 'START_DOWNLOAD') {
    const p = msg.payload || msg;
    let format = (p.format || 'mp4').toLowerCase();
    if (format === 'video') format = 'mp4';
    if (format === 'audio') format = 'mp3';
    if (format === 'low_phone') format = '3gp';

    _loadSettings(s => {
      const body = {
        url: p.url,
        format: format,
        speed: s.defSpeed || 'medium',
        title: p.title || '',
        subtitle_lang: p.subLang || p.subtitle_lang || ''
      };
      if (p.quality && p.quality !== 'best') {
        const qNum = parseInt(p.quality);
        if (!isNaN(qNum)) body.height = qNum;
        else body.quality = p.quality;
      }
      if (s.basePath) body.base_path = s.base_path;
      if (s.folderPlaylist) body.folder_playlist = true;
      if (s.folderChannel) body.folder_channel = true;

      _exportYoutubeCookies(true).finally(() => {
        fetch(SRV + '/download', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        }).then(r => r.json())
          .then(d => {
            _bgSaveQueuedItem(d, body);
            sendResponse({ ok: true, jobId: d.uid || '1', data: d });
          })
          .catch(e => sendResponse({ ok: false, error: { message: String(e) } }));
      });
    });
    return true;
  }

  if (msg.type === 'CHECK_CONNECTION') {
    sendResponse({ state: 'disconnected', serverUrl: SRV });
    return true;
  }

  if (msg.type === 'toggleServer') {
    _toggleServer().then(sendResponse); return true;
  }

  if (msg.type === 'checkServer') {
    fetch(SRV + '/ping', { signal: AbortSignal.timeout(2000) })
      .then(r => r.json()).then(d => sendResponse({ ok: true, data: d }))
      .catch(() => sendResponse({ ok: false }));
    return true;
  }

  if (msg.type === 'CHECK_YONITUBE_SERVER') {
    fetch(SRV + '/ping', { signal: AbortSignal.timeout(2000) })
      .then(r => sendResponse({ online: r.ok }))
      .catch(() => sendResponse({ online: false }));
    return true;
  }

  if (msg.type === 'exportCookies') {
    if (msg.cookies_txt) {
      const now = Date.now();
      const txt = msg.cookies_txt || '';
      const hash = _hashString(txt);
      if (now - _lastCookieExportTs < 20000 && hash === _lastCookieExportHash) {
        sendResponse({ ok: true, skipped: true });
        return true;
      }
      _lastCookieExportTs = now;
      _lastCookieExportHash = hash;
      fetch(SRV + '/update_cookies', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cookies_txt: txt }),
      }).catch(() => {});
      sendResponse({ ok: true });
    } else {
      _exportYoutubeCookies(msg.force).then(() => sendResponse({ ok: true }))
        .catch(() => sendResponse({ ok: false }));
      return true;
    }
    return true;
  }

  if (msg.type === 'openTerms') {
    chrome.tabs.create({ url: chrome.runtime.getURL('terms.html') });
    sendResponse({ ok: true }); return true;
  }

  if (msg.type === 'cancelDownload') {
    fetch(SRV + '/cancel', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ uid: msg.uid }),
    }).then(r => r.json()).then(d => sendResponse({ ok: true, data: d }))
      .catch(() => sendResponse({ ok: false }));
    return true;
  }

  if (msg.type === 'GET_PREFS' || msg.type === 'GET_EXT_SETTINGS') {
    _loadSettings(s => {
      sendResponse({ buttonText: 'הורדה', debug: false, defaultOption: 'video_best', connection: 'disconnected' });
    });
    return true;
  }
});

async function _toggleServer() {
  try {
    const r = await fetch(SRV + '/ping', { signal: AbortSignal.timeout(1500) });
    if (r.ok) {
      await fetch(SRV + '/shutdown', { method: 'POST' }).catch(() => {});
      return { action: 'stopped' };
    }
  } catch {}
  try {
    const port = chrome.runtime.connectNative('com.yonitube.server');
    port.postMessage({ action: 'start' });
    await new Promise(r => setTimeout(r, 2500));
    port.disconnect();
    return { action: 'started' };
  } catch {
    return { action: 'error', msg: 'הפעל YoniTube_Server.exe ידנית' };
  }
}
