console.log('🎵 YouTube Lyrics Extension – Real-Time Synced Lyrics | YT Lyrics');

// SEGMENTED PROGRESS BAR CONFIGURATION
// Boxes map to real operations: cleaning (2) + cache (1) + searches (5)
const PROGRESS_TOTAL_BOXES = 8;

let currentFilledBoxes = 0;
let loadingLabel = '';
let loadingPhaseDescriptions = [];

// Helper to truncate long text for labels
function truncateForLabel(text, maxLength = 35) {
  if (!text || text === 'undefined') return '';
  text = String(text).trim();
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + '...';
}

// Smart Music Video Detection Helper
function isLikelyMusicVideo(title, channelName) {
  const titleLower = title.toLowerCase();
  const channelLower = channelName.toLowerCase();
  
  // DENY LIST - If any of these are found, NOT a music video
  const denyKeywords = ['reaction', 'reacts', 'review', 'reviewed', 'reviewing', 'explained', 'explanation', 'analysis', 'breakdown', 'analyzed', 'how to', 'tutorial', 'guide', 'lesson', 'interview', 'interviewing', 'talks about', 'vlog', 'vlogger', 'daily vlog', 'podcast', 'episode', 'shorts', 'short', 'clip', 'clips', 'highlights', 'highlight', 'best moments'];
  
  // Check deny list first
  for (const keyword of denyKeywords) {
    if (titleLower.includes(keyword)) {
      console.log('❌ Denied by keyword:', keyword);
      return false;
    }
  }
  
  // ALLOW LIST - Music video indicators
  const musicKeywords = ['official video', 'official music video', 'official mv', 'official visualizer', 'official performance video', 'official audio video', 'official audio', 'lyrics', 'lyric video', 'official lyrics', 'with lyrics', 'karaoke', 'sing along', 'singalong', '字幕', '歌詞', '가사', 'lirik', 'vevo', 'umg', 'universal music', 'sony music', 'warner music', 'atlantic records', 'interscope', 'republic records', 'capitol records', 'columbia records', 'def jam', 'auto-generated by youtube', 'provided to youtube by', 'audio', 'visualizer', 'topic', '- topic', 'records', 'music', 'official', 'live', 'live performance', 'live session', 'acoustic', 'unplugged', 'concert', 'on stage', 'radio session', 'tiny desk'];
  
  // Check title for music keywords
  for (const keyword of musicKeywords) {
    if (titleLower.includes(keyword)) {
      console.log('✅ Matched keyword in title:', keyword);
      return true;
    }
  }
  
  // Check channel name for music indicators
  const channelKeywords = ['vevo', 'topic', '- topic', 'official', 'records', 'music', 'umg', 'sony music', 'warner music', 'universal music'];
  
  for (const keyword of channelKeywords) {
    if (channelLower.includes(keyword)) {
      console.log('✅ Matched keyword in channel:', keyword);
      return true;
    }
  }
  
  console.log('⏸️ No music video keywords found');
  return false;
}

// Settings state
let autoShowLyrics = false;
let smartAutoShow = true;

// Tooltip Badge Helper
let tooltipShown = false;



// FREQUENCY FATIGUE - suppress tooltip after 3 consecutive ignores
function getTooltipIgnoreCount() {
  const count = localStorage.getItem('yt_lyrics_tooltip_ignore_count');
  return count ? parseInt(count, 10) : 0;
}

function incrementTooltipIgnoreCount() {
  const count = getTooltipIgnoreCount() + 1;
  localStorage.setItem('yt_lyrics_tooltip_ignore_count', count.toString());
  return count;
}

function resetTooltipIgnoreCount() {
  localStorage.setItem('yt_lyrics_tooltip_ignore_count', '0');
}

function getTooltipSuppressionCount() {
  const count = localStorage.getItem('yt_lyrics_tooltip_suppression_remaining');
  return count ? parseInt(count, 10) : 0;
}

function decrementSuppressionCount() {
  const count = getTooltipSuppressionCount();
  if (count > 0) {
    localStorage.setItem('yt_lyrics_tooltip_suppression_remaining', (count - 1).toString());
  }
}

function startSuppressionCycle() {
  localStorage.setItem('yt_lyrics_tooltip_suppression_remaining', '2');
}

function shouldSuppressTooltip() {
  const suppressionCount = getTooltipSuppressionCount();
  if (suppressionCount > 0) {
    console.log('🔇 Tooltip suppressed, remaining:', suppressionCount);
    // Don't decrement here - let the video change handler do it
    return true;
  }
  
  return false;
}

// ADD NEW FUNCTION to call on video change
function decrementSuppressionOnVideoChange() {
  const suppressionCount = getTooltipSuppressionCount();
  if (suppressionCount > 0) {
    decrementSuppressionCount();
    console.log('🔽 Suppression count decremented, remaining:', getTooltipSuppressionCount());
  }
}

let isWatchPageReady = false;

function checkWatchPageReady() {
  const watchFlexy = document.querySelector('ytd-watch-flexy');
  if (!watchFlexy) return false;
  
  const videoIdAttr = watchFlexy.getAttribute('video-id');
  if (!videoIdAttr) return false;
  
  const urlVideoId = new URLSearchParams(window.location.search).get('v');
  if (videoIdAttr !== urlVideoId) return false;
  
  const titleElement = document.querySelector('ytd-watch-flexy h1.ytd-watch-metadata yt-formatted-string');
  const channelElement = document.querySelector('ytd-watch-flexy ytd-channel-name a');
  
  if (!titleElement || !channelElement) return false;
  if (!titleElement.textContent.trim() || !channelElement.textContent.trim()) return false;
  
  return true;
}

function showLyricsTooltip() {
  // CHECK SUPPRESSION
  if (shouldSuppressTooltip()) {
    console.log('🔇 Tooltip suppressed due to frequency fatigue');
    return;
  }
  
  if (tooltipShown) return;
  
  // DECLARE DURATION FIRST (before using it)
  const isFullscreen = document.fullscreenElement || document.webkitFullscreenElement;
  const tooltipDuration = isFullscreen ? 3000 : 8000;
  console.log('⏱️ Tooltip duration:', tooltipDuration, 'ms');
  
  // Remove any existing tooltip first
  const existingTooltip = document.getElementById('yt-lyrics-tooltip-badge');
  if (existingTooltip) {
    existingTooltip.remove();
  }
  
  const tooltip = document.createElement('div');
  tooltip.id = 'yt-lyrics-tooltip-badge';
  tooltip.innerHTML = '🎵 Click to show lyrics';
  
  // COUNTDOWN SHRINK INDICATOR
  const countdownBar = document.createElement('div');
  countdownBar.style.cssText = `
    position: absolute;
    bottom: 0;
    left: 0;
    height: 3px;
    background: rgba(255, 255, 255, 0.7);
    border-radius: 0 0 12px 12px;
    animation: shrinkCountdown ${tooltipDuration}ms linear forwards;
  `;
  tooltip.appendChild(countdownBar);
  tooltip.style.cssText = `
    position: fixed;
    top: 100px;
    right: 24px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 14px 24px;
    border-radius: 12px;
    font-size: 15px;
    font-weight: 600;
    z-index: 9999999;
    cursor: pointer;
    box-shadow: 0 8px 24px rgba(102, 126, 234, 0.4), 0 4px 8px rgba(0, 0, 0, 0.3);
    transition: all 0.3s ease;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    border: 2px solid rgba(255, 255, 255, 0.3);
    backdrop-filter: blur(10px);
    animation: slideInBounce 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
    @keyframes shrinkCountdown {
        from { width: 100%; }
        to { width: 0%; }
      }
  `;
  
  // Add hover effect
  tooltip.addEventListener('mouseenter', () => {
    tooltip.style.transform = 'scale(1.05) translateY(-2px)';
    tooltip.style.boxShadow = '0 12px 32px rgba(102, 126, 234, 0.5), 0 6px 12px rgba(0, 0, 0, 0.4)';
  });
  
  tooltip.addEventListener('mouseleave', () => {
    tooltip.style.transform = 'scale(1) translateY(0)';
    tooltip.style.boxShadow = '0 8px 24px rgba(102, 126, 234, 0.4), 0 4px 8px rgba(0, 0, 0, 0.3)';
  });
  
  tooltip.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    console.log('🎵 Tooltip clicked - triggering lyrics detection');
    
    // RESET IGNORE COUNT ON CLICK
    resetTooltipIgnoreCount();
    
    // Remove tooltip immediately
    tooltip.remove();
    tooltipShown = true;
    
    // Trigger lyrics detection
    detectAndShowLyrics();
  });
  // Add animation keyframes
  if (!document.getElementById('yt-lyrics-tooltip-animations')) {
    const style = document.createElement('style');
    style.id = 'yt-lyrics-tooltip-animations';
    style.textContent = `
      @keyframes slideInBounce {
        0% {
          transform: translateX(400px);
          opacity: 0;
        }
        60% {
          transform: translateX(-20px);
          opacity: 1;
        }
        80% {
          transform: translateX(10px);
        }
        100% {
          transform: translateX(0);
        }
      }
    `;
    document.head.appendChild(style);
  }
  
  document.body.appendChild(tooltip);
  tooltipShown = true;
  
  setTimeout(() => {
    // INCREMENT IGNORE COUNT IF NOT CLICKED
    const ignoreCount = incrementTooltipIgnoreCount();
    console.log('⏱️ Tooltip ignored, count:', ignoreCount);
    
    if (ignoreCount >= 3) {
      console.log('🔇 Starting suppression cycle (2 videos)');
      startSuppressionCycle();
      resetTooltipIgnoreCount();
    }
    
    tooltip.style.opacity = '0';
    tooltip.style.transform = 'translateX(400px)';
    setTimeout(() => {
      if (tooltip.parentNode) {
        tooltip.remove();
      }
      // RESET FLAG after tooltip is removed
      tooltipShown = false;
      console.log('🔄 Tooltip flag reset');
    }, 300);
  }, tooltipDuration);
}

function shouldAutoShowLyrics(title, channelName) {
  // Never auto-show if disabled
  if (!autoShowLyrics) {
    return false;
  }
  
  // If smart mode is off, always auto-show (legacy behavior)
  if (!smartAutoShow) {
    return true;
  }
  
  // Smart mode: only auto-show for music videos
  return isLikelyMusicVideo(title, channelName);
}

let lyricsPanel = null;
let currentVideoId = null;
let darkModeEnabled = true;
let isMinimized = false;

// STRICT SCROLL STATE - NO TIMERS, NO AUTO-RESUME
let autoScrollEnabled = true;  // Default enabled
let userIsScrolling = false;   // True when user manually scrolls

// CACHE: Track if current request is a refresh (bypasses cache)
let isRefreshRequest = false;

// Load settings (consolidated)
chrome.storage.sync.get(['autoShowLyrics', 'smartAutoShow', 'darkMode'], (result) => {
  autoShowLyrics = result.autoShowLyrics === true;      // Will be false if undefined
  smartAutoShow = result.smartAutoShow !== false;        // Will be true if undefined
  darkModeEnabled = result.darkMode !== false;
  console.log('✅ Settings loaded - autoShow:', autoShowLyrics, 'smartAuto:', smartAutoShow, 'Dark:', darkModeEnabled);
});

// ============================================================================
// SEGMENTED PROGRESS BAR HELPERS
// ============================================================================

/**
 * Reset progress to 0 boxes
 */
function resetProgress() {
  currentFilledBoxes = 0;
  loadingLabel = '';
  loadingPhaseDescriptions = [];
  console.log('🔄 Progress reset to 0 boxes');
}

/**
 * Fill one box after a phase completes (success or failure)
 */
function fillNextBox(phaseLabel = '') {
  if (currentFilledBoxes < PROGRESS_TOTAL_BOXES) {
    currentFilledBoxes++;
    loadingLabel = phaseLabel;
    loadingPhaseDescriptions.push(phaseLabel);
    console.log(`📦 Box ${currentFilledBoxes}/${PROGRESS_TOTAL_BOXES} filled - ${phaseLabel}`);
    updateProgressBarUI();
  }
}

/**
 * Fill all remaining boxes (used on final success)
 */
function fillAllBoxes(label = '') {
  if (currentFilledBoxes < PROGRESS_TOTAL_BOXES) {
    currentFilledBoxes = PROGRESS_TOTAL_BOXES;
    loadingLabel = label;
    console.log(`✅ All boxes filled - ${label}`);
    updateProgressBarUI();
  }
}

/**
 * Render segmented progress bar HTML with dynamically created manual search
 * Using timestamp to ensure fresh input instance (prevents Chrome autofill tracking)
 */
function renderProgressBar() {
  let boxesHTML = '';
  
  for (let i = 0; i < PROGRESS_TOTAL_BOXES; i++) {
    const isFilled = i < currentFilledBoxes;
    const boxClass = isFilled ? 'progress-box-filled' : 'progress-box-empty';
    boxesHTML += `<div class="progress-box ${boxClass}"></div>`;
  }
  
  const percentage = Math.round((currentFilledBoxes / PROGRESS_TOTAL_BOXES) * 100);
  
  // Generate unique ID to prevent Chrome from tracking input across renders
  const uniqueInputId = `manual-search-loading-input-${Date.now()}`;
  const uniqueButtonId = `manual-search-loading-btn-${Date.now()}`;
  
  return `
    <div class="lyrics-loading">
      <div class="segmented-progress-container">
        ${boxesHTML}
      </div>
      <div class="progress-info">
        <span class="progress-label">${loadingLabel}</span>
        <span class="progress-percentage">${percentage}%</span>
      </div>
      <div class="manual-search-box" style="margin-top: 16px;">
        <div class="manual-search-title" style="margin-bottom: 8px; font-size: 12px;">
          <span>⏱️</span>
          <span>Or search manually</span>
        </div>
        <input 
          type="text" 
          class="manual-search-input" 
          placeholder="Artist - Song Title"
          id="${uniqueInputId}"
          name="no-autofill-${Date.now()}"
          autocomplete="new-password"
          autocorrect="off"
          autocapitalize="off"
          spellcheck="false"
          inputmode="search"
          data-form-type="other"
          data-lpignore="true"
          style="margin-bottom: 8px;"
        />
        <button class="manual-search-button" id="${uniqueButtonId}" style="padding: 8px 16px; font-size: 13px;">
          Search Now
        </button>
      </div>
    </div>
  `;
}

/**
 * Update progress bar in DOM (if it exists)
 */
function updateProgressBarUI() {
  const content = document.getElementById('lyrics-content');
  if (!content) return;
  
  // Only update if loading UI is visible
  const loadingDiv = content.querySelector('.lyrics-loading');
  if (loadingDiv) {
    content.innerHTML = renderProgressBar();
    
    // Find dynamically generated input and button by class
    const input = content.querySelector('.manual-search-box .manual-search-input');
    const button = content.querySelector('.manual-search-box .manual-search-button');
    
    if (input && button) {
      setupManualSearchDynamic(input, button, true);
    }
  }
}

// ============================================================================
// LYRICS CACHE SYSTEM
// ============================================================================

const CACHE_MAX_ENTRIES = 200;
const CACHE_MIN_CONFIDENCE = 0.7;

/**
 * Check if video is cacheable (not live stream, has valid duration)
 */
function isVideoCacheable() {
  const video = document.querySelector('video');
  if (!video) return false;
  
  // Check if live stream (duration is Infinity or NaN)
  if (!isFinite(video.duration) || isNaN(video.duration) || video.duration === 0) {
    console.log('⏸️ Video not cacheable: live stream or invalid duration');
    return false;
  }
  
  return true;
}

/**
 * Calculate confidence score for caching decision
 */
function calculateConfidence(parsedData, result, hasMusicSection) {
  let confidence = 0.5; // Base score
  
  // Boost for synced lyrics
  if (result.synced) {
    confidence += 0.2;
  }
  
  // Boost for YouTube Music section
  if (hasMusicSection) {
    confidence += 0.15;
  }
  
  // Boost for official/topic/verified channels
  const channelLower = parsedData.artistFromChannel.toLowerCase();
  if (channelLower.includes('vevo') || 
      channelLower.includes('topic') || 
      channelLower.includes('official')) {
    confidence += 0.15;
  }
  
  // Boost if not a cover
  if (!parsedData.isCover) {
    confidence += 0.1;
  }
  
  return Math.min(confidence, 1.0);
}

/**
 * Get cache key for video ID
 */
function getCacheKey(videoId) {
  return `lyrics_${videoId}`;
}

/**
 * Lookup cached lyrics for video ID
 */
async function getCachedLyrics(videoId) {
  try {
    const cacheKey = getCacheKey(videoId);
    const result = await chrome.storage.local.get(cacheKey);
    
    if (result[cacheKey]) {
      console.log('💾 Cache HIT for video:', videoId);
      return result[cacheKey];
    }
    
    console.log('💨 Cache MISS for video:', videoId);
    return null;
  } catch (error) {
    console.error('❌ Cache read error:', error);
    return null;
  }
}

/**
 * Save lyrics to cache with eviction
 */
async function saveLyricsToCache(videoId, lyricsData, parsedData, channelName, confidence) {
  try {
    // Don't cache if confidence too low
    if (confidence < CACHE_MIN_CONFIDENCE) {
      console.log(`⏭️ Skipping cache: confidence ${confidence.toFixed(2)} < ${CACHE_MIN_CONFIDENCE}`);
      return;
    }
    
    // Don't cache if video not cacheable
    if (!isVideoCacheable()) {
      console.log('⏭️ Skipping cache: video not cacheable');
      return;
    }
    
    const cacheKey = getCacheKey(videoId);
    
    // Build cache entry
    const cacheEntry = {
      lyrics: lyricsData.lyrics,
      synced: lyricsData.synced,
      source: lyricsData.source,
      artist: lyricsData.artist,
      song: lyricsData.song,
      confidence: confidence,
      isCover: parsedData.isCover || false,
      channelName: channelName,
      cachedAt: Date.now()
    };
    
    // Get current metadata
    const metadataResult = await chrome.storage.local.get('lyrics_metadata');
    let metadata = metadataResult.lyrics_metadata || {};
    
    // Add new entry to metadata
    metadata[videoId] = {
      cachedAt: cacheEntry.cachedAt,
      confidence: confidence
    };
    
    // Check if eviction needed
    const entryCount = Object.keys(metadata).length;
    if (entryCount > CACHE_MAX_ENTRIES) {
      console.log(`🗑️ Cache full (${entryCount}/${CACHE_MAX_ENTRIES}), evicting oldest entry`);
      
      // Find oldest entry
      let oldestId = null;
      let oldestTime = Infinity;
      
      for (const [id, meta] of Object.entries(metadata)) {
        if (meta.cachedAt < oldestTime) {
          oldestTime = meta.cachedAt;
          oldestId = id;
        }
      }
      
      if (oldestId) {
        console.log('🗑️ Evicting:', oldestId);
        await chrome.storage.local.remove(getCacheKey(oldestId));
        delete metadata[oldestId];
      }
    }
    
    // Save cache entry and metadata
    await chrome.storage.local.set({
      [cacheKey]: cacheEntry,
      lyrics_metadata: metadata
    });
    
    console.log(`💾 Cached lyrics for ${videoId} (confidence: ${confidence.toFixed(2)})`);
    
  } catch (error) {
    console.error('❌ Cache save error:', error);
  }
}

/**
 * Clear cache entry (used on refresh)
 */
async function clearCachedLyrics(videoId) {
  try {
    const cacheKey = getCacheKey(videoId);
    
    // Remove cache entry
    await chrome.storage.local.remove(cacheKey);
    
    // Update metadata
    const metadataResult = await chrome.storage.local.get('lyrics_metadata');
    let metadata = metadataResult.lyrics_metadata || {};
    
    if (metadata[videoId]) {
      delete metadata[videoId];
      await chrome.storage.local.set({ lyrics_metadata: metadata });
    }
    
    console.log('🗑️ Cleared cache for:', videoId);
  } catch (error) {
    console.error('❌ Cache clear error:', error);
  }
}

// ============================================================================
// AI-POWERED TITLE CLEANER WITH MULTILINGUAL SUPPORT
// ============================================================================

class TitleCleaner {
  constructor() {
    this.patterns = {
      quality: /\b(4K|8K|HD|HQ|UHD|1080p|720p|480p|360p|240p|60fps|120fps)\b/gi,
      brackets: /[\[\(]([^\]\)]*?(official|video|audio|lyric|music|mv|visualizer|premiere|hd|hq|4k|remaster|explicit|clean|radio edit|extended|instrumental|acoustic|live|feat\.|ft\.|featuring|prod\.|produced).*?)[\]\)]/gi,
      phrases: /\b(official music video|official video|official audio|music video|audio|lyric video|lyrics|with lyrics|letra|legendado|tradução|translation|sub español|eng sub|color coded|han rom eng)\b/gi,
      year: /[\[\(]?\b(19|20)\d{2}\b[\]\)]?/g,
      labels: /\b(vevo|records|entertainment|music|productions?|official)\b/gi,
      extra: /[\(\[].*?(remaster|remix|edit|mix).*?[\)\]]$/gi,
      coverDetection: /\s*[\(\[]?\s*(cover|acoustic cover|piano cover|guitar cover|drum cover|vocal cover|remake|reimagined|version by|翻唱|歌ってみた|カバー|커버)\s*[\)\]]?\s*/gi,
      social: /#\w+/g,
      urls: /https?:\/\/\S+/g,
      emojis: /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{1F900}-\u{1F9FF}]|[\u{1FA00}-\u{1FA6F}]/gu,
      spaces: /\s{2,}/g,
      symbols: /^[\s\-\–\—\|]+|[\s\-\–\—\|]+$/g
    };
    
    this.artistSeparators = [
      ' - ', ' – ', ' — ', ' | ', ' • ',
      '・', '·',
      ' / ',
    ];
    
    this.featPatterns = [
      /\s*[\(\[]?\s*feat\.?\s+/gi,
      /\s*[\(\[]?\s*ft\.?\s+/gi,
      /\s*[\(\[]?\s*featuring\s+/gi,
      /\s*[\(\[]?\s*with\s+/gi,
      /\s*[\(\[]?\s*x\s+/gi,
      /\s*[\(\[]?\s*con\s+/gi,
      /\s*[\(\[]?\s*feat\.\s+/gi,
      /\s*[\(\[]?\s*part\.\s+/gi,
      /\s*[\(\[]?\s*feat\s+/gi,
      /\s*×\s*/gi,
    ];
  }
  
  detectLanguage(text) {
    const hasCJK = /[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/.test(text);
    const hasKorean = /[\uac00-\ud7af]/.test(text);
    const hasJapanese = /[\u3040-\u309f\u30a0-\u30ff]/.test(text);
    const hasChinese = /[\u4e00-\u9fff]/.test(text);
    
    if (hasKorean) return 'ko';
    if (hasJapanese) return 'ja';
    if (hasChinese) return 'zh';
    if (/[áéíóúñü]/i.test(text)) return 'es';
    return 'en';
  }
  
  clean(rawTitle, channelName = '', isCover = false) {
    console.log('🧹 Cleaning title:', rawTitle);
    console.log('📺 Channel name:', channelName);
    console.log('🎤 Is cover:', isCover);
    
    // PROGRESS: Box 1 - Start cleaning
    fillNextBox(`Cleaning title: ${truncateForLabel(rawTitle)}`);
    
    let title = rawTitle;
    
    title = title.replace(this.patterns.urls, '');
    title = title.replace(this.patterns.emojis, '');
    title = title.replace(this.patterns.quality, '');
    title = title.replace(this.patterns.phrases, '');
    title = title.replace(this.patterns.year, '');
    title = title.replace(this.patterns.labels, '');
    title = title.replace(this.patterns.brackets, '');
    title = title.replace(this.patterns.extra, '');
    title = title.replace(this.patterns.social, '');
    title = title.replace(this.patterns.spaces, ' ');
    title = title.replace(this.patterns.symbols, '');
    title = title.trim();
    
    console.log('✨ Cleaned title:', title);
    
    return this.parseArtistAndSong(title, channelName, isCover);
  }
  
  cleanChannelName(channelName) {
    if (!channelName) return '';
    
    let cleaned = channelName
      .replace(/\s*-?\s*(official|vevo|topic|music|channel|ost|soundtrack)/gi, '')
      .replace(/\s*-?\s*(lyrics|letra|lyric)/gi, '')
      .trim();
    
    console.log('🎤 Cleaned channel name:', cleaned);
    return cleaned;
  }
  
  parseArtistAndSong(title, channelName = '', isCover = false) {
    let artistFromTitle = '';
    let artistFromChannel = this.cleanChannelName(channelName);
    let song = '';
    let separator = null;
    
    const language = this.detectLanguage(title);
    console.log('🌐 Detected language:', language);
    
    let coverArtist = '';
    const byMatch = title.match(/\s+by\s+(.+?)(?:\s*[\(\[]|$)/i);
    if (byMatch && isCover) {
      coverArtist = byMatch[1].trim();
      console.log('🎤 Detected cover artist:', coverArtist);
      title = title.replace(/\s+by\s+.+?(?=\s*[\(\[]|$)/i, '').trim();
    }
    
    if (language === 'ja' || language === 'zh') {
      if (title.includes('・') || title.includes('·')) {
        const dotSep = title.includes('・') ? '・' : '·';
        const parts = title.split(dotSep);
        if (parts.length >= 2) {
          artistFromTitle = parts[0].trim();
          song = parts.slice(1).join(dotSep).trim();
          separator = dotSep;
          console.log('🎯 Parsed with CJK separator:', dotSep);
        }
      }
      
      if (!song && title.includes('「') && title.includes('」')) {
        const quoteMatch = title.match(/(.+?)「(.+?)」/);
        if (quoteMatch) {
          artistFromTitle = quoteMatch[1].trim();
          song = quoteMatch[2].trim();
          console.log('🎯 Parsed with Japanese quotes');
        }
      }
    }
    
    if (language === 'ko' && !song) {
      for (const sep of [' - ', ' | ', ' – ']) {
        if (title.includes(sep)) {
          const parts = title.split(sep);
          if (parts.length >= 2) {
            artistFromTitle = parts[0].trim();
            song = parts.slice(1).join(sep).trim();
            separator = sep;
            console.log('🎯 Parsed Korean with separator:', sep);
            break;
          }
        }
      }
    }
    
    if (!artistFromTitle || !song) {
      for (const sep of this.artistSeparators) {
        if (title.includes(sep)) {
          const parts = title.split(sep);
          if (parts.length >= 2) {
            artistFromTitle = parts[0].trim();
            song = parts.slice(1).join(sep).trim();
            separator = sep;
            break;
          }
        }
      }
    }
    
    if (!artistFromTitle || !song) {
      const byMatch = title.match(/^(.+?)\s+by\s+(.+)$/i);
      if (byMatch) {
        song = byMatch[1].trim();
        artistFromTitle = byMatch[2].trim();
        console.log('🎯 Parsed "by" pattern');
      }
    }
    
    if (!artistFromTitle && !song) {
      const quoteMatch = title.match(/["'「」]([^"'「」]+)["'「」]/);
      if (quoteMatch) {
        song = quoteMatch[1].trim();
        console.log('🎯 Using quoted text as song title');
      } else {
        song = title;
        console.log('🎯 Using full title as song');
      }
    }
    
    song = this.cleanFeaturing(song);
    song = this.cleanExtraParens(song);
    
    artistFromTitle = this.finalClean(artistFromTitle);
    artistFromChannel = this.finalClean(artistFromChannel);
    song = this.finalClean(song);
    
    console.log('🎯 Parsed - ArtistFromTitle:', artistFromTitle, '| ArtistFromChannel:', artistFromChannel, '| Song:', song, '| CoverArtist:', coverArtist);
    
    return { 
      artistFromTitle, 
      artistFromChannel,
      coverArtist,
      song, 
      originalTitle: title,
      isCover,
      language
    };
  }
  
  cleanExtraParens(text) {
    const endParensPattern = /\s*[\(\[](?:live|version|acoustic|unplugged|demo|instrumental|karaoke|remix|remaster|edit|taylor's version).*?[\)\]]$/gi;
    return text.replace(endParensPattern, '').trim();
  }
  
  cleanFeaturing(text) {
    let cleaned = text;
    for (const pattern of this.featPatterns) {
      const match = cleaned.match(pattern);
      if (match) {
        const index = cleaned.search(pattern);
        cleaned = cleaned.substring(0, index).trim();
        cleaned = cleaned.replace(/[\(\[]$/, '').trim();
      }
    }
    return cleaned;
  }
  
  finalClean(text) {
    return text
      .replace(/^[\s\-\–\—\|•]+|[\s\-\–\—\|•]+$/g, '')
      .replace(/\s{2,}/g, ' ')
      .trim();
  }
  
  generateSearchVariations(parsedData) {
    const { artistFromTitle, artistFromChannel, coverArtist, song, isCover, language } = parsedData;
    const variations = [];
    
    console.log('🔄 Generating variations from:', { artistFromTitle, artistFromChannel, coverArtist, song, isCover, language });
    
    // PROGRESS: Box 2 - Parsing complete
    const displayArtist = artistFromTitle || artistFromChannel || 'Unknown';
    const displaySong = song || 'Unknown';
    fillNextBox(`Parsing: ${truncateForLabel(displayArtist)} – ${truncateForLabel(displaySong)}`);
    
    const songClean = song.replace(this.patterns.coverDetection, '').trim();
    const songNoParens = songClean.replace(/[\(\[].*?[\)\]]/g, '').trim();
    
    if (isCover) {
      console.log('🎤 COVER DETECTED - Generating cover-aware variations');
      
      if (artistFromTitle && songClean) {
        variations.push({ 
          artist: artistFromTitle, 
          song: songClean, 
          source: 'title-artist',
          priority: 1,
          label: 'cover-original-artist' 
        });
      }
      
      if (artistFromChannel && songClean && artistFromChannel !== artistFromTitle) {
        variations.push({ 
          artist: artistFromChannel, 
          song: songClean, 
          source: 'channel',
          priority: 2,
          label: 'cover-channel-artist' 
        });
      }
      
      if (coverArtist && songClean) {
        variations.push({ 
          artist: coverArtist, 
          song: songClean, 
          source: 'cover-artist',
          priority: 3,
          label: 'cover-by-artist' 
        });
      }
      
      if (songClean) {
        variations.push({ 
          artist: '', 
          song: songClean, 
          source: 'song-only',
          priority: 4,
          label: 'cover-song-only' 
        });
      }
      
      if (songNoParens && songNoParens !== songClean) {
        if (artistFromTitle) {
          variations.push({ 
            artist: artistFromTitle, 
            song: songNoParens, 
            source: 'title-artist',
            priority: 5,
            label: 'cover-original-clean' 
          });
        }
        variations.push({ 
          artist: '', 
          song: songNoParens, 
          source: 'song-only',
          priority: 6,
          label: 'cover-song-clean' 
        });
      }
      
    } else {
      console.log('🎵 Regular song - Generating standard variations');
      
      if (artistFromTitle && songClean) {
        variations.push({ 
          artist: artistFromTitle, 
          song: songClean, 
          source: 'title-artist',
          priority: 1,
          label: 'exact' 
        });
      }
      
      if (artistFromChannel && songClean && artistFromChannel !== artistFromTitle) {
        variations.push({ 
          artist: artistFromChannel, 
          song: songClean, 
          source: 'channel',
          priority: 2,
          label: 'channel-as-artist' 
        });
      }
      
      if (artistFromChannel && songClean && artistFromTitle) {
        variations.push({ 
          artist: songClean, 
          song: artistFromChannel, 
          source: 'reversed',
          priority: 3,
          label: 'reversed-search' 
        });
      }
      
      if (songClean) {
        variations.push({ 
          artist: '', 
          song: songClean, 
          source: 'song-only',
          priority: 4,
          label: 'song-only' 
        });
      }
      
      if (songNoParens && songNoParens !== songClean) {
        if (artistFromTitle) {
          variations.push({ 
            artist: artistFromTitle, 
            song: songNoParens, 
            source: 'title-artist',
            priority: 5,
            label: 'no-parens' 
          });
        }
        variations.push({ 
          artist: '', 
          song: songNoParens, 
          source: 'song-only',
          priority: 6,
          label: 'song-only-clean' 
        });
      }
      
      if (artistFromTitle && songClean) {
        variations.push({ 
          artist: '', 
          song: `${artistFromTitle} ${songClean}`, 
          source: 'combined',
          priority: 7,
          label: 'combined-fallback' 
        });
      }
      
      if (artistFromChannel && songClean && artistFromChannel !== artistFromTitle) {
        variations.push({ 
          artist: '', 
          song: `${artistFromChannel} ${songClean}`, 
          source: 'combined',
          priority: 8,
          label: 'combined-channel' 
        });
      }
    }
    
    if (language === 'zh' || language === 'ja' || language === 'ko') {
      const songNoSpaces = songClean.replace(/\s+/g, '');
      if (songNoSpaces !== songClean) {
        if (artistFromTitle) {
          variations.push({ 
            artist: artistFromTitle, 
            song: songNoSpaces, 
            source: 'cjk',
            priority: 9,
            label: 'cjk-no-space' 
          });
        }
        variations.push({ 
          artist: '', 
          song: songNoSpaces, 
          source: 'cjk',
          priority: 10,
          label: 'cjk-song-only' 
        });
      }
      
      const songWithSpaces = songClean.split('').join(' ');
      if (artistFromTitle && songWithSpaces.length < 100) {
        variations.push({ 
          artist: artistFromTitle, 
          song: songWithSpaces, 
          source: 'cjk',
          priority: 11,
          label: 'cjk-spaced' 
        });
      }
    }
    
    variations.sort((a, b) => a.priority - b.priority);
    
    console.log(`✅ Generated ${variations.length} ranked variations`);
    return variations;
  }
  
  removeEmojis(text) {
    return text.replace(this.patterns.emojis, '').replace(/\s{2,}/g, ' ').trim();
  }
}

const titleCleaner = new TitleCleaner();

// ============================================================================
// YOUTUBE INFO EXTRACTION
// ============================================================================

function getChannelName() {
  const watchFlexy = document.querySelector('ytd-watch-flexy');
  if (!watchFlexy) {
    console.log('⚠️ No watch-flexy container found');
    return '';
  }
  
  const selectors = [
    'ytd-channel-name#channel-name yt-formatted-string a',
    'ytd-channel-name#channel-name a',
    '#channel-name a',
    'ytd-video-owner-renderer .ytd-channel-name a',
    '#owner-name a'
  ];
  
  for (const selector of selectors) {
    const element = watchFlexy.querySelector(selector);
    if (element && element.textContent) {
      const channelName = element.textContent.trim();
      console.log('📺 Found channel name:', channelName);
      return channelName;
    }
  }
  
  console.log('⚠️ Could not find channel name');
  return '';
}

function getVideoTitle() {
  const watchFlexy = document.querySelector('ytd-watch-flexy');
  if (!watchFlexy) {
    throw new Error('No watch-flexy container found');
  }
  
  const titleElement = watchFlexy.querySelector('h1.ytd-watch-metadata yt-formatted-string') ||
                      watchFlexy.querySelector('h1.title');
  
  if (!titleElement) {
    throw new Error('Could not find video title');
  }
  
  return titleElement.textContent.trim();
}

function isCoverVideo() {
  const title = getVideoTitle().toLowerCase();
  const description = document.querySelector('#description-inline-expander')?.textContent.toLowerCase() || '';
  
  const coverKeywords = [
    'cover', 'acoustic cover', 'piano cover', 'guitar cover', 'drum cover',
    'vocal cover', 'remake', 'reimagined', 'version by',
    '翻唱', '歌ってみた', 'カバー', '커버'
  ];
  
  const hasCover = coverKeywords.some(keyword => 
    title.includes(keyword) || description.includes(keyword)
  );
  
  console.log('🎤 Is cover video:', hasCover);
  return hasCover;
}

function getMusicInfoFromMusicSection() {
  try {
    const musicRenderers = document.querySelectorAll('ytd-structured-description-content-renderer, ytd-music-description-shelf-renderer');
    
    for (const renderer of musicRenderers) {
      const songElement = renderer.querySelector('.content-title, .title');
      const artistElement = renderer.querySelector('.content-subtitle, .subtitle');
      
      if (songElement && artistElement) {
        let song = songElement.textContent.trim();
        let artist = artistElement.textContent.trim();
        
        song = song.replace(/\s*[\(\[]?\s*(cover|acoustic cover|piano cover|guitar cover|drum cover|vocal cover|remake|reimagined|version by|翻唱|歌ってみた|カバー|커버)\s*[\)\]]?\s*/gi, '').trim();
        
        console.log('🎵 Found Music section info - Song:', song, '| Artist:', artist);
        
        if (song && artist) {
          return { song, artist };
        }
      }
    }
    
    const structuredDesc = document.querySelector('ytd-video-description-music-section-renderer');
    if (structuredDesc) {
      const rows = structuredDesc.querySelectorAll('.item');
      let song = '';
      let artist = '';
      
      rows.forEach(row => {
        const label = row.querySelector('.label')?.textContent.toLowerCase().trim();
        const value = row.querySelector('.value')?.textContent.trim();
        
        if (label === 'song' && value) {
          song = value.replace(/\s*[\(\[]?\s*(cover|acoustic cover|piano cover|guitar cover|drum cover|vocal cover|remake|reimagined|version by|翻唱|歌ってみた|カバー|커버)\s*[\)\]]?\s*/gi, '').trim();
        }
        if (label === 'artist' && value) {
          artist = value;
        }
      });
      
      if (song && artist) {
        console.log('🎵 Found Music section (structured) - Song:', song, '| Artist:', artist);
        return { song, artist };
      }
    }
    
    console.log('⚠️ No Music section found');
    return null;
  } catch (error) {
    console.log('⚠️ Error parsing music section:', error);
    return null;
  }
}

// ============================================================================
// LYRICS SOURCES
// ============================================================================

async function searchLRCLIB(artist, song) {
  try {
    const searches = [
      artist && song ? 
        `https://lrclib.net/api/search?artist_name=${encodeURIComponent(artist)}&track_name=${encodeURIComponent(song)}` 
        : null,
      song ? 
        `https://lrclib.net/api/search?track_name=${encodeURIComponent(song)}`
        : null,
      artist && song ?
        `https://lrclib.net/api/search?q=${encodeURIComponent(`${artist} ${song}`.trim())}`
        : null
    ].filter(Boolean);
    
    for (const url of searches) {
      console.log('🔍 LRCLIB searching:', url);
      const response = await fetch(url);
      
      if (!response.ok) continue;
      
      const results = await response.json();
      
      if (results && results.length > 0) {
        let match = results[0];
        
        if (artist) {
          const exactMatch = results.find(r => 
            r.artistName && r.artistName.toLowerCase().includes(artist.toLowerCase())
          );
          if (exactMatch) match = exactMatch;
        }
        
        console.log('✅ LRCLIB found:', match.trackName, 'by', match.artistName);
        
        if (match.syncedLyrics) {
          return {
            lyrics: match.syncedLyrics,
            synced: true,
            source: 'LRCLIB (Synced)',
            artist: match.artistName,
            song: match.trackName
          };
        } else if (match.plainLyrics) {
          return {
            lyrics: match.plainLyrics,
            synced: false,
            source: 'LRCLIB (Plain)',
            artist: match.artistName,
            song: match.trackName
          };
        }
      }
    }
    
    throw new Error('No results from LRCLIB');
  } catch (error) {
    console.log('❌ LRCLIB failed:', error.message);
    throw error;
  }
}

async function searchLyricsOVH(artist, song) {
  try {
    if (!artist || !song) {
      throw new Error('Artist and song required for Lyrics.ovh');
    }
    
    const url = `https://api.lyrics.ovh/v1/${encodeURIComponent(artist)}/${encodeURIComponent(song)}`;
    console.log('🔍 Lyrics.ovh searching:', url);
    
    const response = await fetch(url);
    
    if (!response.ok) {
      throw new Error('Lyrics.ovh request failed');
    }
    
    const data = await response.json();
    
    if (data.lyrics) {
      console.log('✅ Lyrics.ovh found lyrics');
      return {
        lyrics: data.lyrics,
        synced: false,
        source: 'Lyrics.ovh',
        artist: artist,
        song: song
      };
    }
    
    throw new Error('No lyrics from Lyrics.ovh');
  } catch (error) {
    console.log('❌ Lyrics.ovh failed:', error.message);
    throw error;
  }
}

async function searchAllSources(parsedData) {
  console.log('🚀 Starting multi-source search...');
  console.log('📦 Parsed data:', parsedData);
  
  const variations = titleCleaner.generateSearchVariations(parsedData);
  console.log('🔄 Generated', variations.length, 'search variations');
  
  // Track which major search phases we've tried
  let boxesFilled = {
    titleArtist: false,
    channelArtist: false,
    songOnly: false,
    fallback1: false,
    fallback2: false
  };
  
  for (let i = 0; i < variations.length; i++) {
    const variant = variations[i];
    console.log(`📍 Trying variation ${i + 1}/${variations.length} (${variant.label}):`, { artist: variant.artist, song: variant.song });
    
    // Build dynamic label with real data
    let searchLabel = '';
    if (variant.artist && variant.song) {
      searchLabel = `${truncateForLabel(variant.artist)} – ${truncateForLabel(variant.song)}`;
    } else if (variant.song) {
      searchLabel = `${truncateForLabel(variant.song)}`;
    } else {
      searchLabel = 'Searching...';
    }
    
    // Fill box 3: Artist + Song from title
    if (!boxesFilled.titleArtist && variant.artist && variant.source === 'title-artist') {
      fillNextBox(`Searching: ${searchLabel}`);
      boxesFilled.titleArtist = true;
    }
    // Fill box 4: Channel artist + Song
    else if (!boxesFilled.channelArtist && variant.artist && variant.source === 'channel') {
      fillNextBox(`Channel: ${searchLabel}`);
      boxesFilled.channelArtist = true;
    }
    // Fill box 5: Song-only fallback
    else if (!boxesFilled.songOnly && !variant.artist && variant.source === 'song-only') {
      fillNextBox(`Fallback: ${searchLabel}`);
      boxesFilled.songOnly = true;
    }
    // Fill box 6: Combined/reversed fallbacks
    else if (!boxesFilled.fallback1 && (variant.source === 'combined' || variant.source === 'reversed')) {
      fillNextBox(`Trying: ${searchLabel}`);
      boxesFilled.fallback1 = true;
    }
    // Fill box 7: CJK and final fallbacks
    else if (!boxesFilled.fallback2 && variant.source === 'cjk') {
      fillNextBox(`CJK search: ${searchLabel}`);
      boxesFilled.fallback2 = true;
    }
    
    try {
      const result = await searchLRCLIB(variant.artist, variant.song);
      if (result) {
        console.log(`✅ SUCCESS with variation: ${variant.label}`);
        return result;
      }
    } catch (e) {
      console.log(`  ⏭️  LRCLIB miss (${variant.label})`);
    }
    
    if (variant.artist && variant.song) {
      try {
        const result = await searchLyricsOVH(variant.artist, variant.song);
        if (result) {
          console.log(`✅ SUCCESS with variation: ${variant.label}`);
          return result;
        }
      } catch (e) {
        console.log(`  ⏭️  Lyrics.ovh miss (${variant.label})`);
      }
    }
  }
  
  throw new Error('No lyrics found in any source');
}

// ============================================================================
// UI COMPONENTS
// ============================================================================

function createLyricsPanel() {
  const panel = document.createElement('div');
  panel.id = 'lyrics-extension-panel';
  panel.innerHTML = `
    <style>
      #lyrics-extension-panel {
        position: fixed;
        top: 80px;
        right: 20px;
        width: 380px;
        max-height: 70vh;
        background: ${darkModeEnabled ? 'rgba(28, 28, 30, 0.95)' : 'rgba(255, 255, 255, 0.95)'};
        backdrop-filter: blur(20px) saturate(180%);
        border-radius: 16px;
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        z-index: 999999;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
        border: 1px solid ${darkModeEnabled ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)'};
        transition: height 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        display: flex;
        flex-direction: column;
        overflow: hidden;
      }
      
      #lyrics-extension-panel.minimized {
        height: 60px;
        max-height: 60px;
      }
      
      .lyrics-header {
        flex-shrink: 0;
        padding: 16px 20px;
        background: ${darkModeEnabled ? 'linear-gradient(180deg, #2c2c2e 0%, #1c1c1e 100%)' : 'linear-gradient(180deg, #fafafa 0%, #f0f0f0 100%)'};
        border-bottom: 1px solid ${darkModeEnabled ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)'};
        display: flex;
        justify-content: space-between;
        align-items: center;
        cursor: move;
        user-select: none;
        backdrop-filter: blur(20px);
      }
      
      .lyrics-title {
        font-size: 14px;
        font-weight: 600;
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        display: flex;
        align-items: center;
        gap: 8px;
      }
      
      .lyrics-controls {
        display: flex;
        gap: 8px;
      }
      
      .lyrics-btn {
        width: 28px;
        height: 28px;
        border-radius: 6px;
        border: none;
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)'};
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 14px;
        transition: all 0.2s;
      }
      
      .lyrics-btn:hover {
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.1)'};
        transform: scale(1.05);
      }
      
      .lyrics-content {
        flex: 1;
        overflow-y: auto;
        padding: 20px;
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        line-height: 1.8;
        font-size: 14px;
      }
      
      .lyrics-content::-webkit-scrollbar {
        width: 8px;
      }
      
      .lyrics-content::-webkit-scrollbar-track {
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)'};
        border-radius: 4px;
      }
      
      .lyrics-content::-webkit-scrollbar-thumb {
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.2)'};
        border-radius: 4px;
      }
      
      .lyrics-content::-webkit-scrollbar-thumb:hover {
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.3)' : 'rgba(0, 0, 0, 0.3)'};
      }
      
      .lyrics-loading {
        text-align: center;
        padding: 40px 20px;
        color: ${darkModeEnabled ? '#98989d' : '#86868b'};
      }
      
      .segmented-progress-container {
        display: flex;
        gap: 8px;
        justify-content: center;
        margin-bottom: 16px;
      }
      
      .progress-box {
        width: 36px;
        height: 10px;
        border-radius: 3px;
        transition: none;
        border: 1px solid ${darkModeEnabled ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.12)'};
      }
      
      .progress-box-filled {
        background: ${darkModeEnabled ? 'linear-gradient(90deg, #8E8E93 0%, #AEAEB2 100%)' : 'linear-gradient(90deg, #636366 0%, #8E8E93 100%)'};
        border-color: ${darkModeEnabled ? '#8E8E93' : '#636366'};
        box-shadow: 0 0 3px ${darkModeEnabled ? 'rgba(142, 142, 147, 0.3)' : 'rgba(99, 99, 102, 0.2)'};
      }
      
      .progress-box-empty {
        background: ${darkModeEnabled ? 'rgba(142, 142, 147, 0.08)' : 'rgba(99, 99, 102, 0.06)'};
      }
      
      .progress-info {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 8px;
      }
      
      .progress-label {
        font-size: 13px;
        font-weight: 500;
        color: ${darkModeEnabled ? '#98989d' : '#86868b'};
        flex: 1;
        text-align: left;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      
      .progress-percentage {
        font-size: 12px;
        font-weight: 600;
        color: ${darkModeEnabled ? '#8E8E93' : '#636366'};
        margin-left: 12px;
        flex-shrink: 0;
      }
      
      .manual-search-box {
        background: ${darkModeEnabled ? 'rgba(255, 214, 10, 0.12)' : 'rgba(255, 204, 0, 0.08)'};
        border: 1px solid ${darkModeEnabled ? 'rgba(255, 214, 10, 0.3)' : 'rgba(255, 204, 0, 0.3)'};
        border-radius: 12px;
        padding: 16px;
        margin-top: 16px;
      }
      
      .manual-search-title {
        font-size: 13px;
        font-weight: 600;
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        margin-bottom: 12px;
        display: flex;
        align-items: center;
        gap: 6px;
      }
      
      .manual-search-input {
        width: 100%;
        padding: 10px 12px;
        border: 1px solid ${darkModeEnabled ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.12)'};
        border-radius: 8px;
        font-size: 14px;
        font-family: inherit;
        background: ${darkModeEnabled ? 'rgba(44, 44, 46, 0.9)' : 'rgba(255, 255, 255, 0.9)'};
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        margin-bottom: 10px;
        transition: all 0.2s ease;
        box-sizing: border-box;
      }
      
      .manual-search-input:focus {
        outline: none;
        border-color: ${darkModeEnabled ? '#0A84FF' : '#007AFF'};
        box-shadow: 0 0 0 3px ${darkModeEnabled ? 'rgba(10, 132, 255, 0.15)' : 'rgba(0, 122, 255, 0.1)'};
      }
      
      .manual-search-button {
        width: 100%;
        padding: 10px 16px;
        background: ${darkModeEnabled ? '#0A84FF' : '#007AFF'};
        color: white;
        border: none;
        border-radius: 8px;
        font-size: 14px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s ease;
        font-family: inherit;
      }
      
      .manual-search-button:hover {
        background: ${darkModeEnabled ? '#006EDB' : '#0051D5'};
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(0, 122, 255, 0.3);
      }
      
      .manual-search-button:active {
        transform: translateY(0);
      }
      
      .manual-search-button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
        transform: none;
      }
      
      .manual-search-hint {
        font-size: 11px;
        color: ${darkModeEnabled ? '#98989d' : '#86868b'};
        margin-top: 8px;
        text-align: center;
      }
      
      .lyrics-error {
        text-align: center;
        padding: 40px 20px;
        color: ${darkModeEnabled ? '#ff453a' : '#d70015'};
      }
      
      .lyrics-metadata {
        padding: 12px 20px;
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.03)'};
        border-bottom: 1px solid ${darkModeEnabled ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)'};
        font-size: 12px;
        color: ${darkModeEnabled ? '#98989d' : '#86868b'};
      }
      
      .lyrics-metadata-row {
        display: flex;
        justify-content: space-between;
        margin: 4px 0;
      }
      
      .lyrics-source-badge {
        display: inline-block;
        padding: 4px 8px;
        background: ${darkModeEnabled ? 'rgba(10, 132, 255, 0.2)' : 'rgba(0, 122, 255, 0.1)'};
        color: ${darkModeEnabled ? '#0a84ff' : '#007AFF'};
        border-radius: 4px;
        font-size: 10px;
        font-weight: 600;
        text-transform: uppercase;
      }
      
      .synced-line {
        padding: 8px 0;
        transition: all 0.3s;
        opacity: 0.5;
        cursor: pointer;
      }
      
      .synced-line:hover {
        opacity: 0.8;
        background: ${darkModeEnabled ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)'};
      }
      
      .synced-line.active {
        color: #007AFF;
        font-weight: 600;
        transform: translateX(4px);
        opacity: 1;
        font-size: 15px;
      }
      
      .synced-line.passed {
        opacity: 0.3;
      }
      
      .synced-line.upcoming {
        opacity: 0.5;
      }
      
      .lyrics-minimized-view {
        padding: 16px 20px;
        text-align: center;
      }
      
      .lyrics-minimized-view .mini-line {
        padding: 4px 0;
        font-size: 13px;
        line-height: 1.6;
        transition: all 0.3s;
      }
      
      .lyrics-minimized-view .mini-line.previous,
      .lyrics-minimized-view .mini-line.next {
        opacity: 0.4;
        color: ${darkModeEnabled ? '#98989d' : '#86868b'};
      }
      
      .lyrics-minimized-view .mini-line.current {
        opacity: 1;
        font-weight: 600;
        color: ${darkModeEnabled ? '#f5f5f7' : '#1d1d1f'};
        font-size: 14px;
      }
    </style>
    
    <div class="lyrics-header" id="lyrics-header">
      <div class="lyrics-title">
        <span>🎵</span>
        <span>Lyrics</span>
      </div>
      <div class="lyrics-controls">
        <button class="lyrics-btn" id="minimize-btn" title="Minimize">
          <span style="font-size: 16px; line-height: 1;">−</span>
        </button>
        <button class="lyrics-btn" id="refresh-btn" title="Refresh">
          <span style="font-size: 16px; line-height: 1;">↻</span>
        </button>
        <button class="lyrics-btn" id="close-btn" title="Close">
          <span style="font-size: 16px; line-height: 1;">×</span>
        </button>
      </div>
    </div>
    
    <div class="lyrics-content" id="lyrics-content">
      ${renderProgressBar()}
    </div>
  `;
  
  document.body.appendChild(panel);
  
  // PROGRESS: Reset on refresh
  document.getElementById('refresh-btn').addEventListener('click', () => {
    console.log('🔄 Refresh button clicked - bypassing cache');
    isRefreshRequest = true;
    resetProgress();
    if (window.analytics) {
      window.analytics.trackPanelInteraction('refresh');
    }
    detectAndShowLyrics();
  });
  
  document.getElementById('close-btn').addEventListener('click', () => {
    if (window.analytics) {
      window.analytics.trackPanelInteraction('close');
    }
    
    panel.remove();
    lyricsPanel = null;
  });
  
  document.getElementById('minimize-btn').addEventListener('click', () => {
    panel.classList.toggle('minimized');
    isMinimized = panel.classList.contains('minimized');
    
    if (window.analytics) {
      window.analytics.trackPanelInteraction(isMinimized ? 'minimize' : 'maximize');
    }
    
    // Update lyrics rendering based on minimized state
    if (isMinimized && currentSyncedLines.length > 0) {
      renderMinimizedLyrics();
    } else if (!isMinimized && currentSyncedLines.length > 0) {
      // Restore full lyrics view
      const content = document.getElementById('lyrics-content');
      if (content && content.querySelector('.lyrics-minimized-view')) {
        // Re-render full lyrics
        displayLyrics(currentLyricsResult, currentLyricsResult.isCached);
      }
    }
  });
  
  const lyricsContent = document.getElementById('lyrics-content');
  lyricsContent.addEventListener('scroll', () => {
    if (autoScrollEnabled && !userIsScrolling) {
      userIsScrolling = true;
      console.log('👆 User manually scrolled - auto-scroll PAUSED (will not auto-resume)');
    }
  });
  
  makeDraggable(panel, document.getElementById('lyrics-header'));
  
  return panel;
}

function makeDraggable(element, header) {
  let pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
  
  header.onmousedown = dragMouseDown;
  
  function dragMouseDown(e) {
    if (e.target.closest('.lyrics-btn')) return;
    
    e.preventDefault();
    pos3 = e.clientX;
    pos4 = e.clientY;
    document.onmouseup = closeDragElement;
    document.onmousemove = elementDrag;
    header.style.cursor = 'grabbing';
  }
  
  function elementDrag(e) {
    e.preventDefault();
    
    pos1 = pos3 - e.clientX;
    pos2 = pos4 - e.clientY;
    pos3 = e.clientX;
    pos4 = e.clientY;
    
    let newTop = element.offsetTop - pos2;
    let newLeft = element.offsetLeft - pos1;
    
    const rect = element.getBoundingClientRect();
    const maxTop = window.innerHeight - rect.height;
    const maxLeft = window.innerWidth - rect.width;
    
    newTop = Math.max(0, Math.min(newTop, maxTop));
    newLeft = Math.max(0, Math.min(newLeft, maxLeft));
    
    element.style.top = newTop + "px";
    element.style.left = newLeft + "px";
    element.style.right = 'auto';
  }
  
  function closeDragElement() {
    document.onmouseup = null;
    document.onmousemove = null;
    header.style.cursor = 'move';
  }
}

async function detectAndShowLyrics() {
  try {
    console.log('🎬 Detecting song from YouTube...');
    
    // PROGRESS: Reset progress
    resetProgress();
    
    const rawTitle = getVideoTitle();
    const channelName = getChannelName();
    const isCover = isCoverVideo();
    
    console.log('📺 Raw YouTube title:', rawTitle);
    console.log('📺 Channel name:', channelName);
    console.log('🎤 Is cover:', isCover);

    const videoIdMatch = window.location.search.match(/[?&]v=([^&]+)/);
    const videoId = videoIdMatch ? videoIdMatch[1] : null;
    
    if (window.analytics && videoId) {
      window.analytics.trackVideoViewed(videoId, channelName);
    }
    
    if (!videoId) {
      throw new Error('Could not extract video ID');
    }
    
    if (isRefreshRequest) {
      console.log('🔄 Refresh mode: clearing existing cache for', videoId);
      await clearCachedLyrics(videoId);
      isRefreshRequest = false;
    }
    
    // Boxes 1-2 filled during cleaning/parsing
    const parsedData = titleCleaner.clean(rawTitle, channelName, isCover);
    
    if (!lyricsPanel) {
      lyricsPanel = createLyricsPanel();
    }
    
    const content = document.getElementById('lyrics-content');
    content.innerHTML = renderProgressBar();
    
    // Setup manual search during loading using selector-based approach
    setupManualSearchBySelector('.manual-search-box', true);
    
    // Box 3: Cache lookup (using parsed artist/song if available)
    const displayArtist = parsedData.artistFromTitle || parsedData.artistFromChannel || '';
    const displaySong = parsedData.song || '';
    let cacheLabel = 'Checking cache';
    if (displayArtist && displaySong) {
      cacheLabel = `Cache: ${truncateForLabel(displayArtist)} – ${truncateForLabel(displaySong)}`;
    } else if (displaySong) {
      cacheLabel = `Cache: ${truncateForLabel(displaySong)}`;
    }
    
    if (!isRefreshRequest) {
      fillNextBox(cacheLabel);
      const cachedResult = await getCachedLyrics(videoId);
      if (cachedResult) {
        console.log('💾 Using cached lyrics - skipping search');
        fillAllBoxes('✓ Loaded from cache');
        await new Promise(resolve => setTimeout(resolve, 150)); // Brief visual feedback
        displayLyrics(cachedResult, true);
        return;
      }
    }
    
    // Boxes 4-8: Search sources (filled inside searchAllSources with dynamic labels)
    try {
      const result = await searchAllSources(parsedData);
      
      // Success: fill remaining boxes
      fillAllBoxes('✓ Lyrics found');
      
      const hasMusicSection = getMusicInfoFromMusicSection() !== null;
      const confidence = calculateConfidence(parsedData, result, hasMusicSection);
      console.log('📊 Confidence score:', confidence.toFixed(2));
      
      await saveLyricsToCache(videoId, result, parsedData, channelName, confidence);
      
      displayLyrics(result, false);
      return;
    } catch (error) {
      console.log('❌ Search failed with parsed info, trying Music section...');
      
      const musicInfo = getMusicInfoFromMusicSection();
      
      if (musicInfo && musicInfo.artist && musicInfo.song) {
        console.log('✅ Trying with Music section info');
        
        const musicParsed = {
          artistFromTitle: musicInfo.artist,
          artistFromChannel: '',
          coverArtist: '',
          song: musicInfo.song,
          originalTitle: musicInfo.song,
          isCover: false,
          language: 'en'
        };
        
        const result = await searchAllSources(musicParsed);
        
        fillAllBoxes('✓ Lyrics found');
        
        const confidence = calculateConfidence(musicParsed, result, true);
        await saveLyricsToCache(videoId, result, musicParsed, channelName, confidence);
        
        displayLyrics(result, false);
        return;
      }
      
      throw error;
    }
    
  } catch (error) {
    console.error('❌ Error:', error);
    
    // Fill all boxes on failure
    fillAllBoxes('✗ Not found');

    const rawTitleForError = getVideoTitle();
    if (window.analytics && rawTitleForError) {
      window.analytics.trackLyricsError(rawTitleForError, 'not_found');
    }
    
    if (lyricsPanel) {
      const content = document.getElementById('lyrics-content');
      content.innerHTML = `
        <div class="lyrics-error">
          <div style="font-size: 48px; margin-bottom: 12px;">😔</div>
          <div style="font-weight: 600; margin-bottom: 8px;">Lyrics not found</div>
          <div style="font-size: 12px; opacity: 0.7;">${error.message}</div>
          <div class="manual-search-box">
            <div class="manual-search-title">
              <span>🔍</span>
              <span>Manual Search</span>
            </div>
            <input 
              type="text" 
              class="manual-search-input" 
              placeholder="Artist - Song Title"
              id="manual-search-input-${Date.now()}"
              name="no-autofill-error-${Date.now()}"
              autocomplete="new-password"
              autocorrect="off"
              autocapitalize="off"
              spellcheck="false"
              inputmode="search"
              data-form-type="other"
              data-lpignore="true"
            />
            <button class="manual-search-button" id="manual-search-btn-${Date.now()}">
              Search Again
            </button>
            <div class="manual-search-hint">
              💡 Try typing the exact artist and song name
            </div>
          </div>
        </div>
      `;
      
      setupManualSearchBySelector('.manual-search-box', false);
    }
  }
}

function setupManualSearch(inputId, buttonId, cancelLoading = false) {
  const input = document.getElementById(inputId);
  const button = document.getElementById(buttonId);
  
  if (!input || !button) return;
  
  setupManualSearchDynamic(input, button, cancelLoading);
}

function setupManualSearchBySelector(containerSelector, cancelLoading = false) {
  const container = document.querySelector(containerSelector);
  if (!container) return;
  
  const input = container.querySelector('.manual-search-input');
  const button = container.querySelector('.manual-search-button');
  
  if (!input || !button) return;
  
  setupManualSearchDynamic(input, button, cancelLoading);
}

function setupManualSearchDynamic(input, button, cancelLoading = false) {
  if (!input || !button) return;
  
  // AGGRESSIVE AUTOFILL PREVENTION
  
  // Clear value immediately
  input.value = '';
  
  // Force all anti-autofill attributes
  input.setAttribute('autocomplete', 'new-password');
  input.setAttribute('autocorrect', 'off');
  input.setAttribute('autocapitalize', 'off');
  input.setAttribute('spellcheck', 'false');
  input.setAttribute('inputmode', 'search');
  input.setAttribute('data-lpignore', 'true'); // LastPass ignore
  input.setAttribute('data-form-type', 'other');
  input.setAttribute('name', `no-autofill-${Date.now()}`);
  
  // Clear on focus (Chrome autofill workaround)
  input.addEventListener('focus', () => {
    input.value = '';
    input.setAttribute('autocomplete', 'new-password');
  });
  
  // Clear on blur if empty (prevent Chrome from saving)
  input.addEventListener('blur', () => {
    if (!input.value.trim()) {
      input.value = '';
    }
  });
  
  // Prevent form submission from triggering autosave
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      e.preventDefault();
    }
  });
  
  const performManualSearch = async () => {
    const manualQuery = input.value.trim();
    if (!manualQuery) return;
    
    console.log('🔍 Manual search:', manualQuery);
    
    button.disabled = true;
    button.textContent = '⏳ Searching...';
    
    // PROGRESS: Reset for manual search
    resetProgress();
    
    let manualArtist = '';
    let manualSong = manualQuery;
    
    const separators = [' - ', ' – ', ' — ', ' | '];
    for (const sep of separators) {
      if (manualQuery.includes(sep)) {
        const parts = manualQuery.split(sep);
        manualArtist = parts[0].trim();
        manualSong = parts.slice(1).join(sep).trim();
        break;
      }
    }
    
    try {
      const manualParsed = {
        artistFromTitle: manualArtist,
        artistFromChannel: '',
        coverArtist: '',
        song: manualSong,
        originalTitle: manualSong,
        isCover: false,
        language: 'en'
      };
      
      const result = await searchAllSources(manualParsed);
      
      if (window.analytics) {
        window.analytics.trackManualSearch(manualQuery, result ? true : false);
      }
      
      if (result) {
        fillAllBoxes('✓ Lyrics found');
        
        const videoIdMatch = window.location.search.match(/[?&]v=([^&]+)/);
        const videoId = videoIdMatch ? videoIdMatch[1] : null;
        
        if (videoId) {
          const confidence = 0.8;
          const channelName = getChannelName();
          await saveLyricsToCache(videoId, result, manualParsed, channelName, confidence);
        }
        
        // Clear input after successful search
        input.value = '';
        
        displayLyrics(result, false);
      } else {
        button.textContent = '❌ Still Not Found';
        setTimeout(() => {
          button.disabled = false;
          button.textContent = 'Search Again';
        }, 2000);
      }
    } catch (err) {
      console.error('Manual search error:', err);
      button.textContent = '❌ Not Found';
      setTimeout(() => {
        button.disabled = false;
        button.textContent = cancelLoading ? 'Search Now' : 'Search Again';
      }, 2000);
    }
  };
  
  button.addEventListener('click', performManualSearch);
  input.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
      performManualSearch();
    }
  });
}

function displayLyrics(result, isCached = false) {
  const content = document.getElementById('lyrics-content');
  
  // Store current result for re-rendering (minimize toggle)
  currentLyricsResult = { ...result, isCached };
  
  const cleanArtist = titleCleaner.removeEmojis(result.artist || 'Unknown Artist');
  const cleanSong = titleCleaner.removeEmojis(result.song || 'Unknown Song')
    .replace(/\s*[\(\[]?\s*(cover|acoustic cover|piano cover|guitar cover|drum cover|vocal cover|remake|reimagined|version by|翻唱|歌ってみた|カバー|커버)\s*[\)\]]?\s*/gi, '')
    .trim();
  
  const cacheIndicator = isCached ? '<span style="color: #34C759; margin-left: 8px;">💾 Cached</span>' : '';
  
  let metadata = `
    <div class="lyrics-metadata">
      <div class="lyrics-metadata-row">
        <span>🎤 ${cleanArtist}</span>
        <span class="lyrics-source-badge">${result.source}${cacheIndicator}</span>
      </div>
      <div class="lyrics-metadata-row">
        <span>🎵 ${cleanSong}</span>
        ${result.synced ? '<span style="color: #34C759;">⚡ Synced - Click to seek</span>' : ''}
      </div>
    </div>
  `;
  
  let lyricsHTML = '';
  
  if (result.synced) {
    const lines = result.lyrics.split('\n');
    const parsedLines = [];
    
    lines.forEach(line => {
      const match = line.match(/\[(\d+):(\d+\.\d+)\](.*)/);
      if (match) {
        const minutes = parseInt(match[1]);
        const seconds = parseFloat(match[2]);
        const text = match[3].trim();
        const timeInSeconds = minutes * 60 + seconds;
        
        if (text) {
          parsedLines.push({
            time: timeInSeconds,
            text: text
          });
        }
      }
    });
    
    parsedLines.forEach((line, index) => {
      lyricsHTML += `<div class="synced-line upcoming" data-time="${line.time}" data-index="${index}">${line.text}</div>`;
    });
    
    setTimeout(() => {
      const lineElements = document.querySelectorAll('.synced-line');
      lineElements.forEach(lineElement => {
        lineElement.addEventListener('click', function() {
          const time = parseFloat(this.getAttribute('data-time'));
          const video = document.querySelector('video');
          if (video && !isNaN(time)) {
            video.currentTime = time;
            userIsScrolling = false;
            console.log('⏩ Seeked to:', time, 'seconds | Auto-scroll RE-ENABLED via lyric click');
          }
        });
      });
      
      startLyricsSync(parsedLines);
    }, 100);
    
  } else {
    lyricsHTML = result.lyrics
      .split('\n')
      .map(line => `<div>${line || '<br>'}</div>`)
      .join('');
  }
  
  const compactSearchPrompt = `
    <div class="manual-search-box" style="margin: 16px 20px; padding: 12px;">
      <div class="manual-search-title" style="margin-bottom: 8px; font-size: 12px;">
        <span>🔍</span>
        <span>Wrong song? Type it manually</span>
      </div>
      <input 
        type="text" 
        class="manual-search-input" 
        placeholder="Artist - Song Title"
        id="manual-search-input-top-${Date.now()}"
        name="no-autofill-top-${Date.now()}"
        autocomplete="new-password"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
        inputmode="search"
        data-form-type="other"
        data-lpignore="true"
        style="margin-bottom: 8px;"
      />
      <button class="manual-search-button" id="manual-search-btn-top-${Date.now()}" style="padding: 8px 16px; font-size: 13px;">
        Search Different Song
      </button>
    </div>
  `;
  
  content.innerHTML = metadata + compactSearchPrompt + `<div style="padding: 0 20px 20px 20px;">${lyricsHTML}</div>`;
  
  if (window.analytics) {
    window.analytics.trackLyricsDisplayed(cleanArtist, cleanSong, result.source, result.synced);
  }
  
  // Setup manual search using selector-based approach (works with dynamic IDs)
  setupManualSearchBySelector('.manual-search-box', false);
}

let currentSyncedLines = [];
let syncInterval = null;
let currentLyricsResult = null;
let currentActiveLineIndex = -1;

function startLyricsSync(parsedLines) {
  currentSyncedLines = parsedLines;
  
  if (syncInterval) {
    clearInterval(syncInterval);
  }
  
  syncInterval = setInterval(updateLyricsHighlight, 100);
  
  console.log('✅ Lyrics sync started with', parsedLines.length, 'lines');
}

function renderMinimizedLyrics() {
  const content = document.getElementById('lyrics-content');
  if (!content || currentSyncedLines.length === 0) return;
  
  const activeIndex = currentActiveLineIndex;
  
  let previousLine = '';
  let currentLine = '';
  let nextLine = '';
  
  if (activeIndex > 0) {
    previousLine = currentSyncedLines[activeIndex - 1].text;
  }
  
  if (activeIndex >= 0 && activeIndex < currentSyncedLines.length) {
    currentLine = currentSyncedLines[activeIndex].text;
  }
  
  if (activeIndex >= 0 && activeIndex < currentSyncedLines.length - 1) {
    nextLine = currentSyncedLines[activeIndex + 1].text;
  }
  
  // Fallback if no active line yet
  if (!currentLine && currentSyncedLines.length > 0) {
    currentLine = currentSyncedLines[0].text;
    if (currentSyncedLines.length > 1) {
      nextLine = currentSyncedLines[1].text;
    }
  }
  
  const miniLyricsHTML = `
    <div class="lyrics-minimized-view">
      <div class="mini-line previous">${previousLine || '•••'}</div>
      <div class="mini-line current">${currentLine || 'No lyrics playing'}</div>
      <div class="mini-line next">${nextLine || '•••'}</div>
    </div>
  `;
  
  content.innerHTML = miniLyricsHTML;
}

function updateLyricsHighlight() {
  const video = document.querySelector('video');
  if (!video || !currentSyncedLines.length) return;
  
  const currentTime = video.currentTime;
  
  let activeIndex = -1;
  for (let i = 0; i < currentSyncedLines.length; i++) {
    if (currentTime >= currentSyncedLines[i].time) {
      activeIndex = i;
    } else {
      break;
    }
  }
  
  currentActiveLineIndex = activeIndex;
  
  // If minimized, render 3-line view instead of highlighting full list
  if (isMinimized) {
    renderMinimizedLyrics();
    return;
  }
  
  // Full lyrics mode
  const lineElements = document.querySelectorAll('.synced-line');
  lineElements.forEach((element, index) => {
    element.classList.remove('active', 'passed', 'upcoming');
    
    if (index === activeIndex) {
      element.classList.add('active');
    } else if (index < activeIndex) {
      element.classList.add('passed');
    } else {
      element.classList.add('upcoming');
    }
  });
  
  // Only auto-scroll if NOT minimized and auto-scroll enabled
  if (!isMinimized && autoScrollEnabled && !userIsScrolling && activeIndex >= 0 && lineElements[activeIndex]) {
    const container = document.getElementById('lyrics-content');
    const activeLine = lineElements[activeIndex];
    
    if (container) {
      const containerRect = container.getBoundingClientRect();
      const lineRect = activeLine.getBoundingClientRect();
      
      if (lineRect.top < containerRect.top || lineRect.bottom > containerRect.bottom) {
        activeLine.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }
  }
}

function observeVideoChanges() {
  const videoIdMatch = window.location.search.match(/[?&]v=([^&]+)/);
  const newVideoId = videoIdMatch ? videoIdMatch[1] : null;
  
  if (newVideoId && newVideoId !== currentVideoId) {
    currentVideoId = newVideoId;
    console.log('🎬 New video detected:', currentVideoId);
    
    if (lyricsPanel) {
      console.log('🗑️ Closing existing lyrics panel');
      lyricsPanel.remove();
      lyricsPanel = null;
    }
    
    // PROGRESS: Reset on video change
    resetProgress();
    
    // Reset minimized state and lyrics data
    isMinimized = false;
    currentSyncedLines = [];
    currentLyricsResult = null;
    currentActiveLineIndex = -1;
    
    if (syncInterval) {
      clearInterval(syncInterval);
      syncInterval = null;
    }
    
    tooltipShown = false;
    isWatchPageReady = false;
    autoScrollEnabled = true;
    userIsScrolling = false;
    isRefreshRequest = false;
    
    console.log('🔄 State reset - autoScroll: enabled, userScrolling: false, minimized: false');
    
    decrementSuppressionOnVideoChange();
    
    const checkTitle = setInterval(() => {
      if (!checkWatchPageReady()) {
        console.log('⏸️ Watch page not ready, waiting...');
        return;
      }
      
      isWatchPageReady = true;
      
      const watchFlexy = document.querySelector('ytd-watch-flexy');
      if (!watchFlexy) {
        console.log('⏸️ No watch-flexy found');
        return;
      }
      
      const titleElement = watchFlexy.querySelector('h1.ytd-watch-metadata yt-formatted-string');
      const channelElement = watchFlexy.querySelector('ytd-channel-name a');
      
      if (titleElement && titleElement.textContent.trim()) {
        clearInterval(checkTitle);
        
        const title = titleElement.textContent.trim();
        const channelName = channelElement?.textContent.trim() || '';
        
        console.log('✅ Video title loaded:', title);
        console.log('📺 Channel:', channelName);
        console.log('⚙️ Settings - autoShowLyrics:', autoShowLyrics, 'smartAutoShow:', smartAutoShow);
        
        const isMusicVideo = isLikelyMusicVideo(title, channelName);
        console.log('🎵 Is music video?', isMusicVideo);
        
        let shouldAutoShow = false;
        let shouldShowTooltip = false;
        
        if (autoShowLyrics && smartAutoShow) {
          shouldAutoShow = true;
          console.log('✅ Will auto-show (auto ON + smart ON = always show)');
        }
        else if (autoShowLyrics && !smartAutoShow) {
          shouldAutoShow = true;
          console.log('✅ Will auto-show (auto ON + smart OFF = always show)');
        }
        else if (!autoShowLyrics && smartAutoShow) {
          if (isMusicVideo) {
            shouldAutoShow = true;
            console.log('✅ Will auto-show (auto OFF + smart ON + music video)');
          } else {
            shouldShowTooltip = true;
            console.log('🔔 Will show tooltip (auto OFF + smart ON + NOT music video)');
          }
        }
        else if (!autoShowLyrics && !smartAutoShow) {
          shouldShowTooltip = true;
          console.log('🔔 Will show tooltip (auto OFF + smart OFF = always tooltip)');
        }
        
        if (shouldAutoShow) {
          setTimeout(() => {
            detectAndShowLyrics();
          }, 1000);
        } else if (shouldShowTooltip) {
          setTimeout(() => {
            showLyricsTooltip();
          }, 2000);
        }
      }
    }, 500);
    
    setTimeout(() => clearInterval(checkTitle), 10000);
  }
}

let lastUrl = location.href;
new MutationObserver(() => {
  const url = location.href;
  if (url !== lastUrl) {
    lastUrl = url;
    observeVideoChanges();
  }
}).observe(document, { subtree: true, childList: true });

if (document.readyState === 'complete') {
  observeVideoChanges();
} else {
  window.addEventListener('load', () => {
    setTimeout(() => {
      observeVideoChanges();
    }, 1000);
  });
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log('📨 Message received:', request.action);
  
  if (request.action === 'detectSong') {
    detectAndShowLyrics();
    sendResponse({ success: true });
  }
  
  if (request.action === 'updateAutoShow') {
    autoShowEnabled = request.enabled;
    console.log('🔄 Auto-show updated:', autoShowEnabled);
    sendResponse({ success: true });
    if (window.analytics) {
      window.analytics.trackAutoDisplayToggle(request.enabled);
    }
  }

  if (request.action === 'updateSmartAutoShow') {
    smartAutoShow = request.enabled;
    console.log('🎯 Smart auto-show updated:', smartAutoShow);
    sendResponse({ success: true });
  }
  
  if (request.action === 'updateDarkMode') {
    darkModeEnabled = request.enabled;
    console.log('🌙 Dark mode updated:', darkModeEnabled);
    if (window.analytics) {
      window.analytics.trackThemeToggle(request.enabled);
    } 
    if (lyricsPanel) {
      const wasMinimized = lyricsPanel.classList.contains('minimized');
      lyricsPanel.remove();
      lyricsPanel = null;
      detectAndShowLyrics();
      if (wasMinimized) {
        setTimeout(() => {
          lyricsPanel?.classList.add('minimized');
        }, 100);
      }
    }
    
    sendResponse({ success: true });
  }
  
  if (request.action === 'refreshExtension') {
    console.log('🔄 Refreshing extension...');
    
    if (lyricsPanel) {
      lyricsPanel.remove();
      lyricsPanel = null;
    }
    
    currentVideoId = null;
    
    chrome.storage.sync.get(['autoShowLyrics', 'smartAutoShow', 'darkMode'], (result) => {
      autoShowLyrics = result.autoShowLyrics === true;
      smartAutoShow = result.smartAutoShow !== false;
      darkModeEnabled = result.darkMode !== false;
      console.log('✅ Settings reloaded');
      observeVideoChanges();
    });
    
    sendResponse({ success: true });
  }
  
  return true;
});

console.log('✅ YTLyrics loaded successfully!');

if (window.analytics) {
  window.analytics.trackEvent('extension_loaded', {
    page: 'youtube_watch'
  });
} else {
  console.log('⚠️ Analytics not available yet, waiting...');
  setTimeout(() => {
    if (window.analytics) {
      window.analytics.trackEvent('extension_loaded', {
        page: 'youtube_watch'
      });
    }
  }, 1000);
}