name: Automate Organization Invites
on:
  issues:
    types: [opened]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'invite me')
    steps:
      - name: Send Invite
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: 'https-mitmachim-top'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'ברוך הבא לארגון! ההזמנה נשלחה לחשבון שלך.'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
