name: Automate Organization Invites
on:
  issues:
    types: [opened]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'invite') || contains(github.event.issue.title, 'הזמן')
    steps:
      - name: Send Invite
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: 'https-mitmachim-top'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'ברוך הבא לארגון מתמחים טופ! ההזמנה הרשמית נשלחה לחשבון שלך. יש לאשר אותה במייל או דרך עמוד הארגון בגיטהאב.'
          teams: 'developers'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
