name: Automate Organization Invites
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'invite') || contains(github.event.issue.title, 'הזמן')
    steps:
      - name: Auto Invite Member
        uses: cloudposse/github-action-auto-invite@main
        with:
          organization: 'https-mitmachim-top'
          github_token: ${{ secrets.GITHUB_TOKEN }}
